OLED_DRIVER_ENABLE = yes   # Enables the use of OLED displays
OLED_ENABLE = yes
OLED_DRIVER = SSD1306   # Enables the use of OLED displays
WPM_ENABLE = no

RGBLIGHT_ENABLE = yes      # Enable keyboard RGB underglow

MOUSEKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes
STENO_ENABLE = no
BOOTMAGIC_ENABLE =no
TERMINAL_ENABLE = no
KEY_LOCK_ENABLE = no
AUDIO_ENABLE = no
CONSOLE_ENABLE = no
VELOCIKEY_ENABLE = no

LTO_ENABLE = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
EXTRAKEY_ENABLE = no

SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no

AVR_USE_MINIMAL_PRINTF = yes
